### ISSUE TITLE
Add cards into kitchen sink & unify their style

### ISSUE THREAD

**Issue by codeknitter** [edlio/uniform#29]
Unify card styles in framework:

- [x] **dashboard**
border-radius: 3px;
box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
remove border

![dashboard-cards](https://user-images.githubusercontent.com/5893954/42064142-b9b02df4-7afa-11e8-9e7d-9bfd8f9f1c55.png)

- [x] **web stats**
border-radius: 3px;
box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
remove border

![web-stats-cards](https://user-images.githubusercontent.com/5893954/42064074-6450a398-7afa-11e8-856e-66966b086fe2.png)

- [x] **info box**
border-radius: 3px;
box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
(NO border, keep grey background)

![info-box](https://user-images.githubusercontent.com/5893954/42064000-0d33331e-7afa-11e8-90c5-2e189afb5e0c.png)

- [x] **warning/confirmation message boxes**
border-radius: 3px;
(NO box-shadow, keep green border)

![confirmation-msg](https://user-images.githubusercontent.com/5893954/42064193-e840c2f0-7afa-11e8-8929-1cc88e2713fd.png)

**Comment by skempisty** [comment]
PR for this is here https://github.com/edlio/uniform/pull/48

Still adding cards - I'll merge to master once they're all done.

**Comment by skempisty** [comment]
FYI Warning/confirmation boxes are already covered in "Notifications". Gonna hit the checkbox on that one and move on.

**Comment by skempisty** [comment]
Merged PR. Closing!
