### ISSUE TITLE
Uniform component: sticky bottom toolbar for save/cancel

### ISSUE THREAD

**Issue by codeknitter** [edlio/uniform#42]
# Context
Right now there isn't consistency across features in terms of placement and accessibility of save button. Goals of this component:

- Make bottom save bar sticky so it doesn't get lost below the fold.
- Consistency
- Accessibility 

# Acceptance Criteria

Component elements will differ based on requirements of feature:
- [ ] Primary action button on right - required, label may be Save, Publish or something else
- [ ] Secondary action buttons to left of main action button - optional
- [ ] Notices to left of secondary action button - optional
- [ ] Cancel on left  - optional 
- [ ] Buttons must be accessible within flow of content on page. Reach out to @tim-robinson when testing to confirm accessibility of entire component

When viewing very bottom of page:
- [ ] toolbar's top border is 1px solid #cccccc 
- [ ] no top shadow
- [ ] make sure entire page is visible above toolbar 
![toolbar at bottom of page](https://user-images.githubusercontent.com/5893954/42348999-dec7b7c6-8070-11e8-851a-a2bddc1e52be.png)

When page is scrolled up:
- [ ] toolbar has no border 
- [ ] add top shadow
![toolbar when scrolled up](https://user-images.githubusercontent.com/5893954/42349003-e0bdba30-8070-11e8-87e1-6722d8d8f6bb.png)

```
.edlio.cms .bar {
    display: block;
    margin: 0;
    padding-top: .5em;
    padding-bottom: .75em;
    position: fixed;
    bottom: 0;
    right: 0;
    left: 0;
    background: #fff;
    /* when scrolled up  -->  box-shadow: 0 -2px 2px 0 rgba(0,0,0,0.14); */
    /* when at bottom of page --> border-top: 1px solid #ccc; */
}
```

**Comment by lancedolan** [comment]
Incorporating into tech notes here: https://github.com/edlio/cms/issues/5618
