### ISSUE TITLE
Bug: Display issue with toggle in Windows Chrome. The toggle button is drooping below the toggle area.

### ISSUE THREAD

**Issue by RodrickYuEdlio** [edlio/uniform#5]
![image](https://user-images.githubusercontent.com/34290938/41685649-f585ec80-7495-11e8-8b4b-72b6d7043cff.png)
![image](https://user-images.githubusercontent.com/34290938/41685658-fdc8e014-7495-11e8-9aad-1fb2e4374605.png)

**Comment by skempisty** [comment]
Honestly could not figure this one out. Please tell me what you did when someone fixes this because this frustrated me to no end

**Comment by RodrickYuEdlio** [comment]
With the little I know about this stuff, I believe the issue has to do with different font metrics for OSX and Windows. This causes the variance in line height of the parent label element which results in the difference in positioning for the toggle button. The only way I can think of to line them up in all platforms would be to absolute position the toggle back plate (are there real names for these things?) so that both parts of the toggle are positioned exactly by pixel.

**Comment by jbaeedlio** [comment]
Font-related issue. Avenir was specified but not imported. hence depending on system support.
#7 brought open sans and also imported from google docs, so we now have promised font consistency across browsers and systems.
commit 0db4420 simply adjusted position for new font.
