### ISSUE TITLE
Fix extra & incorrect colors

### ISSUE THREAD

**Issue by codeknitter** [edlio/uniform#69]
Uniform contains some extra colors that aren't in the official color palette. 

$selection-blue - What is this being used for? It's not in the [original color palette](https://edlioinc.atlassian.net/wiki/spaces/UX/pages/2949629/Color).  If there is a legitimate case for using it please let me know what that is. Otherwise it needs to be removed.

$red - the official hex code for Edlio Red is #D22630, not #e64017

**Comment by MichaelLiEdlio** [comment]
in cms two places use $election-blue
photos.scss  .album.list select checked   (shoved project for replaceing albums but not active anymore)
shuffles.scss  .mobile-shuffle-setting checked 
![image](https://user-images.githubusercontent.com/34312020/48447482-d6af1b00-e750-11e8-8283-3f9d113967f2.png)

I do agree the color usage is really odd
should just be using $blue

**Comment by codeknitter** [comment]
- any $red errors should be switched to $orange as we update those features
- $edlio-red is #D22630 per https://edlioinc.atlassian.net/wiki/spaces/MKTG/pages/4129368/Edlio+Colors+Logo+and+Corporate+Identity+files  (#CB1A10 was the old color for edlio red)
- we should switch $selection-blue to $blue as we can. if we need to keep $selection-blue around for while that's ok as long as we mark it as deprecated and don't use it any new places
