### ISSUE TITLE
Include FontAwesome and CMS custom SVG to Uniform Repository.

### ISSUE THREAD

**Issue by rcliao** [edlio/uniform#8]

**Comment by MichaelLiEdlio** [comment]
All icons from [CMS Icon Library](https://edlioinc.atlassian.net/wiki/spaces/UX/pages/2359323/Edlio+CMS+Icon+Library) has been added to uniform except

- 0146-book2.svg  update to book-open.svg from fontawesome
- 0385-drawer3.svg update to drawer.svg(093-drawer.svg)
- 0505-user-cancel.svg removed 
- 0506-user-block.svg  removed
- 0874-menu2.svg removed

for custom icons update prefix name edlio_ to edlio-
for icomoon icons remove prefix num-
